# Generated by Django 4.1.7 on 2023-03-02 05:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='fees',
            new_name='Fees',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='lastname',
            new_name='LastName',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='roll_no',
            new_name='Roll_No',
        ),
        migrations.AddField(
            model_name='students',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
