# Generated by Django 4.1.7 on 2023-03-02 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_fees_students_fees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='address',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
